CREATE VIEW VIEW_USER_INFORMATION AS
SELECT USERS.*,
		USER_CURRENT_CITIES.CURRENT_CITY_ID,
		CURRENT_CITIES.CITY_NAME AS CURRENT_CITY,
		CURRENT_CITIES.STATE_NAME AS CURRENT_STATE,
		CURRENT_CITIES.COUNTRY_NAME AS CURRENT_COUNTRY,
		USER_HOMETOWN_CITIES.HOMETOWN_CITY_ID,
		HOMETOWN_CITIES.CITY_NAME AS HOMETOWN_CITY,
		HOMETOWN_CITIES.STATE_NAME AS HOMETOWN_STATE,
		HOMETOWN_CITIES.COUNTRY_NAME AS HOMETOWN_COUNTRY,
		EDUCATION.PROGRAM_ID AS PROGRAM_ID,
		EDUCATION.PROGRAM_YEAR AS PROGRAM_YEAR,
		PROGRAMS.INSTITUTION AS INSTITUTION_NAME,
		PROGRAMS.CONCENTRATION AS PROGRAM_CONCENTRATION,
		PROGRAMS.DEGREE AS PROGRAM_DEGREE
FROM USERS
LEFT JOIN
USER_CURRENT_CITIES ON
USERS.USER_ID=USER_CURRENT_CITIES.USER_ID
LEFT JOIN CITIES CURRENT_CITIES ON
USER_CURRENT_CITIES.CURRENT_CITY_ID=CURRENT_CITIES.CITY_ID
LEFT JOIN
USER_HOMETOWN_CITIES ON
USERS.USER_ID=USER_HOMETOWN_CITIES.USER_ID
LEFT JOIN CITIES HOMETOWN_CITIES ON
USER_HOMETOWN_CITIES.HOMETOWN_CITY_ID=HOMETOWN_CITIES.CITY_ID
LEFT JOIN
EDUCATION ON
USERS.USER_ID = EDUCATION.USER_ID
LEFT JOIN
PROGRAMS ON
EDUCATION.PROGRAM_ID = PROGRAMS.PROGRAM_ID;

CREATE VIEW VIEW_ARE_FRIENDS AS
SELECT * FROM FRIENDS;

CREATE VIEW VIEW_PHOTO_INFORMATION AS
SELECT ALBUMS.ALBUM_ID, ALBUMS.ALBUM_OWNER_ID, ALBUMS.COVER_PHOTO_ID,
        ALBUMS.ALBUM_NAME, ALBUMS.ALBUM_CREATED_TIME, ALBUMS.ALBUM_MODIFIED_TIME,
        ALBUMS.ALBUM_LINK, ALBUMS.ALBUM_VISIBILITY, PHOTOS.PHOTO_ID,
        PHOTOS.PHOTO_CAPTION, PHOTOS.PHOTO_CREATED_TIME, PHOTOS.PHOTO_MODIFIED_TIME,
        PHOTOS.PHOTO_LINK
FROM ALBUMS
INNER JOIN PHOTOS ON ALBUMS.ALBUM_ID=PHOTOS.ALBUM_ID;

CREATE VIEW VIEW_EVENT_INFORMATION AS
SELECT USER_EVENTS.EVENT_ID, USER_EVENTS.EVENT_CREATOR_ID, USER_EVENTS.EVENT_NAME,
        USER_EVENTS.EVENT_TAGLINE, USER_EVENTS.EVENT_DESCRIPTION, USER_EVENTS.EVENT_HOST,
        USER_EVENTS.EVENT_TYPE, USER_EVENTS.EVENT_SUBTYPE, USER_EVENTS.EVENT_ADDRESS,
        CITIES.CITY_NAME, CITIES.STATE_NAME, CITIES.COUNTRY_NAME, 
        USER_EVENTS.EVENT_START_TIME, USER_EVENTS.EVENT_END_TIME
FROM USER_EVENTS
INNER JOIN CITIES ON USER_EVENTS.EVENT_CITY_ID=CITIES.CITY_ID;

CREATE VIEW VIEW_TAG_INFORMATION AS
SELECT * FROM TAGS;
