CREATE VIEW VIEW_USER_INFORMATION AS
SELECT USER.USER_ID, USER.FIRST_NAME, USER.LAST_NAME,
        USER.YEAR_OF_BIRTH, USER.MONTH_OF_BIRTH, USER.DAY_OF_BIRTH,
        USER.GENDER ...
;

CREATE VIEW VIEW_ARE_FRIENDS AS
SELECT * FROM FRIENDS;

CREATE VIEW VIEW_PHOTO_INFORMATION AS
SELECT ALBUMS.ALBUM_ID, ALBUMS.ALBUM_OWNER_ID, ALBUMS.COVER_PHOTO_ID,
        ALBUMS.ALBUM_NAME, ALBUM.ALBUM_CREATED_TIME, ALBUM.ALBUM_MODIFIED_TIME,
        ALBUM.ALBUM_LINK, ALBUM.ALBUM_VISIBILITY, PHOTO.PHOTO_ID,
        PHOTO.PHOTO_CAPTION, PHOTO.PHOTO_CREATED_TIME, PHOTO.PHOTO_MODIFIED_TIME,
        PHOTO.PHOTO_LINK
FROM ALBUMS
INNER JOIN PHOTO ON ALBUM.ALBUM_ID=PHOTO.ALBUM_ID;

CREATE VIEW VIEW_EVENT_INFORMATION AS
;

CREATE VIEW VIEW_TAG_INFORMATION AS
;
